server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.105.134.96:3306/business
      username: root
      password: Wz930819!
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5
  mvc:
    static-path-patten:/static/**
mybatis:
  mapper-locations: classpath*:com/wz/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    com.wz.dao: debug

#  pagehelper.helper-dialect=mysql
#  pagehelper.reasonable=true
#  pagehelper.support-methods-arguments=true
#  pagehelper.params=countSql







